// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("backend.Models.TBL01", b =>
                {
                    b.Property<int>("L01F01")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("L01F02")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("user_type");

                    b.Property<string>("L01F03")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("full_name");

                    b.Property<string>("L01F04")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("L01F05")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("phone");

                    b.Property<DateTime>("L01F06")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dob");

                    b.Property<string>("L01F07")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.Property<DateTime>("L01F08")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.HasKey("L01F01");

                    b.HasIndex("L01F04")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("backend.Models.TBL02", b =>
                {
                    b.Property<int>("L02F01")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("L02F02")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<string>("L02F03")
                        .HasColumnType("longtext")
                        .HasColumnName("emergency_contact");

                    b.Property<string>("L02F04")
                        .HasColumnType("longtext")
                        .HasColumnName("allergies");

                    b.Property<DateTime>("L02F05")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("L02F07")
                        .HasColumnType("longtext")
                        .HasColumnName("blood_group");

                    b.Property<int?>("L02F08")
                        .HasColumnType("int")
                        .HasColumnName("height_cm");

                    b.Property<int?>("L02F09")
                        .HasColumnType("int")
                        .HasColumnName("weight_kg");

                    b.Property<string>("L02F10")
                        .HasColumnType("longtext")
                        .HasColumnName("chronic_conditions");

                    b.HasKey("L02F01");

                    b.HasIndex("L02F02")
                        .IsUnique();

                    b.ToTable("patients", (string)null);
                });

            modelBuilder.Entity("backend.Models.TBL03", b =>
                {
                    b.Property<int>("L03F01")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("L03F02")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<string>("L03F03")
                        .HasColumnType("longtext")
                        .HasColumnName("specialization");

                    b.Property<string>("L03F04")
                        .HasColumnType("longtext")
                        .HasColumnName("license_number");

                    b.Property<int?>("L03F05")
                        .HasColumnType("int")
                        .HasColumnName("years_experience");

                    b.Property<DateTime>("L03F06")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("L03F08")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("bio");

                    b.Property<decimal>("L03F10")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("consultation_fee");

                    b.Property<decimal>("L03F11")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("rating_avg");

                    b.Property<int>("L03F12")
                        .HasColumnType("int")
                        .HasColumnName("total_reviews");

                    b.HasKey("L03F01");

                    b.ToTable("doctors", (string)null);
                });

            modelBuilder.Entity("backend.Models.TBL04", b =>
                {
                    b.Property<int>("L04F01")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("L04F02")
                        .HasColumnType("int")
                        .HasColumnName("patient_user_id");

                    b.Property<int>("L04F03")
                        .HasColumnType("int")
                        .HasColumnName("doctor_user_id");

                    b.Property<DateTime>("L04F04")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("appointment_at_utc");

                    b.Property<string>("L04F05")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("reason");

                    b.Property<string>("L04F06")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<string>("L04F07")
                        .HasColumnType("longtext")
                        .HasColumnName("doctor_notes");

                    b.Property<DateTime>("L04F08")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("L04F09")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("L04F10")
                        .HasColumnType("int")
                        .HasColumnName("clinic_id");

                    b.Property<int>("L04F11")
                        .HasColumnType("int")
                        .HasColumnName("slot_id");

                    b.HasKey("L04F01");

                    b.HasIndex("L04F02", "L04F04");

                    b.HasIndex("L04F03", "L04F04");

                    b.ToTable("appointments", (string)null);
                });

            modelBuilder.Entity("backend.Models.TBL05", b =>
                {
                    b.Property<int>("L05F01")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("L05F02")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("L05F03")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("address_line");

                    b.Property<string>("L05F04")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("city");

                    b.Property<string>("L05F05")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("state");

                    b.Property<string>("L05F06")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("pincode");

                    b.Property<decimal>("L05F07")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("L05F08")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("longitude");

                    b.Property<string>("L05F09")
                        .HasColumnType("longtext")
                        .HasColumnName("phone");

                    b.Property<DateTime>("L05F10")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.HasKey("L05F01");

                    b.ToTable("clinics", (string)null);
                });

            modelBuilder.Entity("backend.Models.TBL06", b =>
                {
                    b.Property<int>("L06F01")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("L06F02")
                        .HasColumnType("int")
                        .HasColumnName("doctor_user_id");

                    b.Property<int>("L06F03")
                        .HasColumnType("int")
                        .HasColumnName("clinic_id");

                    b.Property<decimal?>("L06F04")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("consultation_fee");

                    b.Property<DateTime>("L06F05")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.HasKey("L06F01");

                    b.HasIndex("L06F03");

                    b.HasIndex("L06F02", "L06F03")
                        .IsUnique();

                    b.ToTable("doctor_clinics", (string)null);
                });

            modelBuilder.Entity("backend.Models.TBL07", b =>
                {
                    b.Property<int>("L07F01")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("L07F02")
                        .HasColumnType("int")
                        .HasColumnName("doctor_user_id");

                    b.Property<int>("L07F03")
                        .HasColumnType("int")
                        .HasColumnName("clinic_id");

                    b.Property<DateTime>("L07F04")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("slot_start_utc");

                    b.Property<DateTime>("L07F05")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("slot_end_utc");

                    b.Property<bool>("L07F06")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_booked");

                    b.Property<DateTime>("L07F07")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.HasKey("L07F01");

                    b.HasIndex("L07F03");

                    b.HasIndex("L07F02", "L07F03", "L07F04")
                        .IsUnique();

                    b.ToTable("appointment_slots", (string)null);
                });

            modelBuilder.Entity("backend.Models.TBL02", b =>
                {
                    b.HasOne("backend.Models.TBL01", "L02F06")
                        .WithOne("L01F09")
                        .HasForeignKey("backend.Models.TBL02", "L02F02")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("L02F06");
                });

            modelBuilder.Entity("backend.Models.TBL03", b =>
                {
                    b.HasOne("backend.Models.TBL01", "L03F07")
                        .WithOne("L01F10")
                        .HasForeignKey("backend.Models.TBL03", "L03F02")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("L03F07");
                });

            modelBuilder.Entity("backend.Models.TBL04", b =>
                {
                    b.HasOne("backend.Models.TBL01", null)
                        .WithMany()
                        .HasForeignKey("L04F02")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.TBL01", null)
                        .WithMany()
                        .HasForeignKey("L04F03")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend.Models.TBL06", b =>
                {
                    b.HasOne("backend.Models.TBL03", "L06F06")
                        .WithMany()
                        .HasForeignKey("L06F02")
                        .HasPrincipalKey("L03F02")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.TBL05", "L06F07")
                        .WithMany()
                        .HasForeignKey("L06F03")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("L06F06");

                    b.Navigation("L06F07");
                });

            modelBuilder.Entity("backend.Models.TBL07", b =>
                {
                    b.HasOne("backend.Models.TBL03", "L07F08")
                        .WithMany()
                        .HasForeignKey("L07F02")
                        .HasPrincipalKey("L03F02")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.TBL05", "L07F09")
                        .WithMany()
                        .HasForeignKey("L07F03")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("L07F08");

                    b.Navigation("L07F09");
                });

            modelBuilder.Entity("backend.Models.TBL01", b =>
                {
                    b.Navigation("L01F09");

                    b.Navigation("L01F10");
                });
#pragma warning restore 612, 618
        }
    }
}
